### ISSUE TITLE
error while building vulkan-loader-git

### ISSUE THREAD

**Issue by Danhyal-Masood** [jb-alvarado/media-autobuild_suite#1281]
01:14:30 └ vulkan-loader-git ................................. [Updated]
01:14:30 ├ Running cmake...
Likely error:
CMake Error at D:/media-autobuild_suite-master/media-autobuild_suite-master/msys64/mingw64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find WDK (missing: WDK_VERSION_INCLUDE_DIR)
Call Stack (most recent call first):
  D:/media-autobuild_suite-master/media-autobuild_suite-master/msys64/mingw64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindWDK.cmake:61 (find_package_handle_standard_args)
  CMakeLists.txt:121 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/media-autobuild_suite-master/media-autobuild_suite-master/build/vulkan-loader-git/build-64bit/CMakeFiles/CMakeOutput.log".
cmake failed. Check D:/media-autobuild_suite-master/media-autobuild_suite-master/build/vulkan-loader-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.

log:
[z9zG.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3384428/z9zG.zip)

**Comment by wiiaboo** [comment]
Fixed by patch author.

**Comment by tcmbackwards** [comment]
Still not working, looks like it's missing dependencies now
https://0x0.st/z9pW.zip

**Comment by LigH-de** [comment]
Unfortunately, vulkan-loader still gets built when I select a Zeranoe compatible GPL-3 ffmpeg license combination; in this case, the option `--disable-vulkan` in **mpv_options.txt** is not used, but instead some internal defaults. I will temporarily edit my **media-autobuild_suite.bat** line 107 to skip it:

```
 :: overriden defaults
-set mpv_options_basic=--disable-debug-build "--lua=luajit"
+set mpv_options_basic=--disable-debug-build "--lua=luajit" --disable-vulkan
 
```

**Comment by 1480c1** [comment]
It seems with https://github.com/KhronosGroup/Vulkan-Loader/commit/b423f800487bae4ff451d148dde4589a05eb3674, they have made the [WDK](https://en.wikipedia.org/wiki/Windows_Driver_Kit) a requirement and put new instructions for it https://github.com/KhronosGroup/Vulkan-Loader/commit/232d005adfa10f758ea3cfdca63b758d49080291

**Comment by 1480c1** [comment]
@wiiaboo, either we can pin at v1.1.114 without the wdk requirements or drop it (although I don't want to) since I can't get wdk to do a silent install nor can I force it to install to a separate directory. I'm right now trying to see if there is any way around installing wdk / installing wdk without affecting outside the suite

**Comment by wiiaboo** [comment]
Why did they suddenly add such a huge dependency?

**Comment by 1480c1** [comment]
it seems it was for this commit https://github.com/KhronosGroup/Vulkan-Loader/commit/6eb61431a4217b3eef75e59b1c70e25fc37b8064

**Comment by tcmbackwards** [comment]
What was the resolution? Disable vulkan or drop mpv?

**Comment by wiiaboo** [comment]
Why the hell would mpv be dropped? If you don't want it don't build it. It's the second most useful thing being built by the suite after FFmpeg.

**Comment by 1480c1** [comment]
> What was the resolution? Disable vulkan or drop mpv?

The resolution is to just bind to a vulkan-loader that doesn't require WDK, unless they can make a separate config without requiring WDK

**Comment by tcmbackwards** [comment]
Why would it? I'm confused. Were you talking about vulkan loader? I thought you were responding to ligh saying he could just disable vulkan when building mpv. I thought you were talking about dropping mpv there.

I want mpv, i don't care about vulkan, especially if it now has a WDK dependency.

**Comment by LigH-de** [comment]
My suggestion of a temporary workaround was disabling vulkan for mpv; but now the solution is to [clamp a version before WDK was required](https://github.com/jb-alvarado/media-autobuild_suite/commit/cd967e1996ac4cbcf53f647d132979361132015f).
