### ISSUE TITLE
build is failing at mpv package

### ISSUE THREAD

**Issue by projalepeno** [jb-alvarado/media-autobuild_suite#475]
Hi -- build is failing at mpv package.  **[logs.zip](https://0x0.st/4ge.zip)**

Thanks for any help.

Details:

┌ mpv git .............................................. [Updates found]
├ Running configure...
├ Running build...
Likely error:
<line>Displays current media-title or filename</line> line
<line>Shows current cache fill status</line> line
<line>Shows current playback position timestamp</line> line
<line>Indicates current playback position and position of chapters</line> line
<line>Shows remaining playback time timestamp</line> line
<line>Displays selected track and amount of available tracks</line> line

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check G:/media-autobuild_suite-master/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/4ge.zip
Copy and paste [logs.zip](https://0x0.st/4ge.zip) in the GitHub issue.

**Comment by wiiaboo** [comment]
Upload the _cache.py file inside `\build\mpv-git\build\c4che\`.

**Comment by ASopH** [comment]
I've seen these issue and run my mas.. same issue

**Comment by ASopH** [comment]
uploading doesn't go: .. zip doesn't go,
here plain txt:
------snip-----
AR = ['/mingw32/bin/ar']
ARFLAGS = ['rcs']
BINDIR = '/local32/bin-video'
BIN_PERL = ['/usr/bin/perl']
CC = ['gcc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('6', '3', '0')
CFLAGS = ['-mthreads', '-mtune=generic', '-O2', '-pipe', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-D_WIN32_WINNT=0x0601', '-DUNICODE', '-DCOBJMACROS', '-DINITGUID', '-U__STRICT_ANSI__', '-municode', '-D__USE_MINGW_ANSI_STDIO=1', '-isystem', '/build/mpv-git/osdep/win32/include', '-I', '/build/mpv-git/osdep/win32/include', '-DIN_WINPTHREAD']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_compiler = ['-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls']
CFLAGS_cshlib = []
CFLAGS_libav = ['-mconsole', '-mconsole', '-mconsole']
CFLAGS_libavcodec = ['-mconsole']
CFLAGS_libavdevice = ['-mconsole', '-mconsole', '-mconsole', '-mconsole']
COMPILER_CC = 'gcc'
CONFDIR = '/local32/etc/mpv'
CONFLOADDIR = '/local32/etc/mpv'
CPPFLAGS = ['-D_FORTIFY_SOURCE=2', '-D__USE_MINGW_ANSI_STDIO=1']
CPPPATH_ST = '-I%s'
CXXFLAGS_libav = ['-mconsole', '-mconsole', '-mconsole']
CXXFLAGS_libavcodec = ['-mconsole']
CXXFLAGS_libavdevice = ['-mconsole', '-mconsole', '-mconsole', '-mconsole']
DATADIR = '/local32/share'
DEFINES = []
DEFINES_ST = '-D%s'
DEFINE_COMMENTS = {'HAVE_BSD_FSTATFS': '', 'HAVE_ZLIB': '', 'HAVE_LIBASS': '', 'HAVE_VAAPI': '', 'HAVE_VAPOURSYNTH_LAZY': '', 'HAVE_LIBM': '', 'HAVE_PLAIN_GL': '', 'HAVE_DLOPEN': '', 'HAVE_XEXT': '', 'HAVE_JACK': '', 'HAVE_GNUC': '', 'HAVE_DVDNAV': '', 'HAVE_OPTIMIZE': '', 'HAVE_AUDIOUNIT': '', 'HAVE_LIBRT': '', 'HAVE_POSIX_OR_MINGW': '', 'HAVE_VF_DLOPEN_FILTERS': '', 'HAVE_OSX_THREAD_NAME': '', 'HAVE_APPLE_REMOTE': '', 'HAVE_LIBAV': '', 'HAVE_NETBSD_THREAD_NAME': '', 'HAVE_AVUTIL_IMGCPY_UC': '', 'HAVE_GL_X11': '', 'HAVE_MALI_FBDEV': '', 'HAVE_RUBBERBAND': '', 'HAVE_VIDEOTOOLBOX_VIDEOTOOLBOX_H': '', 'HAVE_DIRECT3D': '', 'HAVE_IOS_GL': '', 'HAVE_ANY_GL': '', 'HAVE_OSS_AUDIO_4FRONT': '', 'HAVE_TEST': '', 'HAVE_ANDROID': '', 'HAVE_SHM': '', 'HAVE_GLOB': '', 'HAVE_IS_FFMPEG': '', 'HAVE_EGL_DRM': '', 'HAVE_LIBBLURAY': '', 'HAVE_FCHMOD': '', 'HAVE_BSD_THREAD_NAME': '', 'HAVE_LUAJIT': '', 'HAVE_VIDEOTOOLBOX_HWACCEL': '', 'HAVE_EGL_ANGLE_LIB': '', 'HAVE_LIBARCHIVE': '', 'HAVE_CUDA_HWACCEL': '', 'HAVE_ENCODING': '', 'HAVE_TV': '', 'HAVE_DEBUG_BUILD': '', 'HAVE_VAAPI_X_EGL': '', 'HAVE_GL': '', 'HAVE_EGL_X11': '', 'HAVE_EGL_ANGLE': '', 'HAVE_OPENSLES': '', 'HAVE_POSIX_SPAWN': '', 'DEFAULT_CDROM_DEVICE': '', 'HAVE_CPLUGINS': '', 'DEFAULT_DVD_DEVICE': '', 'HAVE_GBM_H': '', 'HAVE_BUILD_DATE': '', 'HAVE_LIBDL': '', 'HAVE_DVBIN': '', 'HAVE_DRM': '', 'HAVE_GLOB_WIN32_REPLACEMENT': '', 'HAVE_STDATOMIC': '', 'HAVE_RPI': '', 'HAVE_ICONV': '', 'HAVE_LIBMPV_SHARED': '', 'HAVE_VAAPI_HWACCEL_NEW': '', 'HAVE_XRANDR': '', 'HAVE_CACA': '', 'HAVE_SOUNDCARD_H': '', 'HAVE_NANOSLEEP': '', 'HAVE_POSIX': '', 'HAVE_ATOMICS': '', 'HAVE_STANDARD_GL': '', 'HAVE_JPEG': '', 'HAVE_VAPOURSYNTH_CORE': '', 'HAVE_PULSE': '', 'HAVE_GBM': '', 'HAVE_VIDEO_TOOLBOX_VIDEO_TOOLBOX_H': '', 'HAVE_GL_COCOA': '', 'HAVE_COREAUDIO': '', 'HAVE_SYS_TERMIOS_H': '', 'HAVE_DOS_PATHS': '', 'HAVE_LIBV4L2': '', 'HAVE_SSE4_INTRINSICS': '', 'FULLCONFIG': '', 'HAVE_VAAPI_WAYLAND': '', 'HAVE_VIDEOTOOLBOX_GL': '', 'HAVE_NOEXECSTACK': '', 'HAVE_D3D_HWACCEL': '', 'HAVE_XINERAMA': '', 'HAVE_SYS_VIDEOIO_H': '', 'HAVE_TV_V4L2': '', 'HAVE_ASM': '', 'HAVE_VAAPI_GLX': '', 'HAVE_CPLAYER': '', 'HAVE_MINGW': '', 'HAVE_ANDROID_GL': '', 'HAVE_LIBAVCODEC_DXVA2_H': '', 'HAVE_LIBAVDEVICE': '', 'HAVE_LIBMPV_STATIC': '', 'HAVE_XSS': '', 'HAVE_AUDIO_INPUT': '', 'HAVE_SDL1': '', 'HAVE_WASAPI': '', 'HAVE_TERMIOS': '', 'HAVE_OSS_AUDIO_SUNAUDIO': '', 'HAVE_LCMS2': '', 'HAVE_OSS_AUDIO': '', 'HAVE_VT_H': '', 'HAVE_LIBSMBCLIENT': '', 'HAVE_OSS_AUDIO_NATIVE': '', 'HAVE_VDPAU_GL_X11': '', 'HAVE_RSOUND': '', 'HAVE_CLANG_DATABASE': '', 'HAVE_GL_WAYLAND': '', 'HAVE_DUMMY_OSD': '', 'HAVE_ZSH_COMP': '', 'HAVE_CDDA': '', 'HAVE_VAAPI_EGL': '', 'HAVE_COCOA': '', 'HAVE_C11_TLS': '', 'HAVE_WIN32': '', 'HAVE_VDPAU_HWACCEL': '', 'HAVE_STATIC_BUILD': '', 'HAVE_GCC_TLS': '', 'HAVE_SYS_SOUNDCARD_H': '', 'HAVE_ALSA': '', 'HAVE_SNDIO': '', 'HAVE_XV': '', 'HAVE_DVDREAD': '', 'HAVE_TERMIOS_H': '', 'HAVE_SUBPROCESS': '', 'HAVE_IS_LIBAV': '', 'HAVE_VAAPI_DRM': '', 'HAVE_LUA': '', 'HAVE_VAPOURSYNTH': '', 'HAVE_VIDEODEV': '', 'HAVE_LIBASS_OSD': '', 'HAVE_GL_DXINTEROP': '', 'HAVE_WIN32_INTERNAL_PTHREADS': '', 'HAVE_VAAPI_X11': '', 'HAVE_OPENAL': '', 'HAVE_LINUX_FSTATFS': '', 'CONFIGURATION': '', 'HAVE_X11': '', 'HAVE_VAAPI_HWACCEL': '', 'HAVE_LIBAVCODEC_D3D11VA_H': '', 'HAVE_SDL2': '', 'HAVE_VDPAU': '', 'HAVE_UCHARDET': '', 'HAVE_VAAPI_HWACCEL_OLD': '', 'HAVE_GLIBC_THREAD_NAME': '', 'HAVE_LIBAVCODEC': '', 'MPV_CONFDIR': '', 'HAVE_GL_WIN32': '', 'HAVE_WAYLAND': '', 'HAVE_EGL_HELPERS': ''}
DEST_BINFMT = 'pe'
DEST_CPU = 'x86'
DEST_OS = 'win32'
DOCDIR = '/local32/share/doc/mpv'
HAVE_C11_TLS = 1
HAVE_CUDA_HWACCEL = 1
HAVE_D3D_HWACCEL = 1
HAVE_DIRECT3D = 1
HAVE_DVDNAV = 1
HAVE_DVDREAD = 1
HAVE_GCC_TLS = 1
HAVE_GL_DXINTEROP = 1
HAVE_GL_WIN32 = 1
HAVE_GNUC = 1
HAVE_ICONV = 1
HAVE_IS_FFMPEG = 1
HAVE_JPEG = 1
HAVE_LCMS2 = 1
HAVE_LIBARCHIVE = 1
HAVE_LIBASS = 1
HAVE_LIBAV = 1
HAVE_LIBAVCODEC = 1
HAVE_LIBAVDEVICE = 1
HAVE_LIBBLURAY = 1
HAVE_LIBDL = 1
HAVE_LIBM = 1
HAVE_LUAJIT = 1
HAVE_MINGW = 1
HAVE_NOEXECSTACK = 1
HAVE_RUBBERBAND = 1
HAVE_SSE4_INTRINSICS = 1
HAVE_STANDARD_GL = 1
HAVE_STDATOMIC = 1
HAVE_UCHARDET = 1
HAVE_WASAPI = 1
HAVE_WIN32 = 1
HAVE_ZLIB = 1
HTMLDIR = '/local32/share/doc/mpv'
IMPLIB_ST = '-Wl,--out-implib,%s'
INCDIR = '/local32/include'
INCLUDES_dvdnav = ['F:/m-a-s/local32/include']
INCLUDES_dvdread = ['F:/m-a-s/local32/include']
INCLUDES_lcms2 = ['F:/m-a-s/msys64/mingw32/include']
INCLUDES_libarchive = ['F:/m-a-s/msys64/mingw32/include']
INCLUDES_libass = ['F:/m-a-s/local32/include', 'F:/m-a-s/local32/include/harfbuzz', 'F:/m-a-s/local32/include/fribidi', 'F:/m-a-s/local32/include/freetype2', 'F:/m-a-s/msys64/mingw32/include', 'F:/m-a-s/msys64/mingw32/include/libpng16']
INCLUDES_libav = ['F:/m-a-s/local32/include']
INCLUDES_libavcodec = ['F:/m-a-s/local32/include']
INCLUDES_libavdevice = ['F:/m-a-s/local32/include']
INCLUDES_libbluray = ['F:/m-a-s/local32/include']
INCLUDES_luajit = ['F:/m-a-s/msys64/mingw32/include/luajit-2.0']
INCLUDES_rubberband = ['F:/m-a-s/local32/include/rubberband']
INCLUDES_uchardet = ['/mingw32/include/uchardet']
LAST_LINKFLAGS = ['-Wl,--major-os-version=6,--minor-os-version=0', '-Wl,--major-subsystem-version=6,--minor-subsystem-version=0', '-municode', '-mwindows']
LDFLAGS = ['-pipe', '-static-libgcc', '-static-libstdc++', '-L/local32/lib', '-L/mingw32/lib']
LIBDIR = '/local32/lib'
LIBPATH_ST = '-L%s'
LIBRARY_PATH = ['F:/m-a-s/local32/lib;F:/m-a-s/msys64/mingw32/lib']
LIB_ST = '-l%s'
LIB_gl_win32 = ['opengl32']
LIB_iconv = ['iconv']
LIB_jpeg = ['jpeg']
LIB_libdl = ['dl']
LIB_libm = ['m']
LIB_win32 = ['winmm', 'gdi32', 'ole32', 'uuid', 'avrt', 'dwmapi']
LIB_zlib = ['z']
LINKFLAGS = ['-Wl,--enable-auto-import']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINKFLAGS_iconv = ['-LF:/m-a-s/local32/lib;F:/m-a-s/msys64/mingw32/lib']
LINKFLAGS_libav = ['-Wl,--no-undefined', '-Wl,--no-undefined', '-Wl,--no-undefined']
LINKFLAGS_libavcodec = ['-Wl,--no-undefined']
LINKFLAGS_libavdevice = ['-Wl,--no-undefined', '-Wl,--no-undefined', '-Wl,--no-undefined', '-Wl,--no-undefined']
LINKFLAGS_noexecstack = ['-Wl,--nxcompat', '-Wl,--no-seh', '-Wl,--dynamicbase']
LINK_CC = ['gcc']
MANDIR = '/local32/share/man'
PKG_CONFIG = ['/mingw32/bin/pkg-config', '--static']
PREFIX = '/local32'
RPATH_ST = '-Wl,-rpath,%s'
RST2HTML = ['/mingw32/bin/rst2html3']
RST2MAN = ['/mingw32/bin/rst2man3']
RST2PDF = ['/mingw32/bin/rst2pdf']
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIBPATH_dvdnav = ['F:/m-a-s/local32/lib']
STLIBPATH_dvdread = ['F:/m-a-s/local32/lib']
STLIBPATH_lcms2 = ['F:/m-a-s/msys64/mingw32/lib']
STLIBPATH_libarchive = ['F:/m-a-s/msys64/mingw32/lib']
STLIBPATH_libass = ['/local32/lib','/mingw32/lib']
STLIBPATH_libav = ['/local32/lib','/mingw32/lib']
STLIBPATH_libavcodec = ['F:/m-a-s/local32/lib', 'F:/m-a-s/msys64/mingw32/lib', '/local32/lib', 'F:/m-a-s/local32/lib']
STLIBPATH_libavdevice = ['/local32/lib','/mingw32/lib']
STLIBPATH_libbluray = ['F:/m-a-s/local32/lib']
STLIBPATH_luajit = ['F:/m-a-s/msys64/mingw32/lib']
STLIBPATH_rubberband = ['F:/m-a-s/local32/lib']
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
STLIB_dvdnav = ['dvdnav', 'dvdread', 'dl']
STLIB_dvdread = ['dvdread', 'dl']
STLIB_lcms2 = ['lcms2', 'm']
STLIB_libarchive = ['archive', 'crypto', 'nettle', 'regex', 'expat', 'lzo2', 'lzma', 'lz4', 'bz2', 'z', 'bcrypt']
STLIB_libass = ['ass', 'm', 'iconv', 'harfbuzz', 'fribidi', 'freetype', 'z', 'bz2', 'png16', 'z']
STLIB_libav = ['avfilter', 'ws2_32', 'dl', 'avicap32', 'gdi32', 'psapi', 'ole32', 'strmiids', 'uuid', 'oleaut32', 'shlwapi', 'user32', 'dl', 'iconv', 'secur32', 'mingw32', 'SDL2main', 'SDL2', 'mingw32', 'SDL2main', 'SDL2', 'm', 'dinput8', 'dxguid', 'dxerr8', 'user32', 'gdi32', 'winmm', 'imm32', 'ole32', 'oleaut32', 'shell32', 'version', 'uuid', 'gcrypt', 'gpg-error', 'x265', 'stdc++', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'advapi32', 'shell32', 'user32', 'kernel32', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'x264', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vorbisenc', 'vorbis', 'ogg', 'opus', 'm', 'mp3lame', 'm', 'lzma', 'bz2', 'z', 'psapi', 'advapi32', 'shell32', 'swscale', 'm', 'postproc', 'avformat', 'ws2_32', 'dl', 'avicap32', 'gdi32', 'psapi', 'ole32', 'strmiids', 'uuid', 'oleaut32', 'shlwapi', 'user32', 'dl', 'iconv', 'secur32', 'mingw32', 'SDL2main', 'SDL2', 'mingw32', 'SDL2main', 'SDL2', 'm', 'dinput8', 'dxguid', 'dxerr8', 'user32', 'gdi32', 'winmm', 'imm32', 'ole32', 'oleaut32', 'shell32', 'version', 'uuid', 'gcrypt', 'gpg-error', 'x265', 'stdc++', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'advapi32', 'shell32', 'user32', 'kernel32', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'x264', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vorbisenc', 'vorbis', 'ogg', 'opus', 'm', 'mp3lame', 'm', 'lzma', 'bz2', 'z', 'psapi', 'advapi32', 'shell32', 'avcodec', 'ws2_32', 'dl', 'avicap32', 'gdi32', 'psapi', 'ole32', 'strmiids', 'uuid', 'oleaut32', 'shlwapi', 'user32', 'dl', 'iconv', 'secur32', 'mingw32', 'SDL2main', 'SDL2', 'mingw32', 'SDL2main', 'SDL2', 'm', 'dinput8', 'dxguid', 'dxerr8', 'user32', 'gdi32', 'winmm', 'imm32', 'ole32', 'oleaut32', 'shell32', 'version', 'uuid', 'gcrypt', 'gpg-error', 'x265', 'stdc++', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'advapi32', 'shell32', 'user32', 'kernel32', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'x264', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vorbisenc', 'vorbis', 'ogg', 'opus', 'm', 'mp3lame', 'm', 'lzma', 'bz2', 'z', 'psapi', 'advapi32', 'shell32', 'swresample', 'm', 'avutil', 'm']
STLIB_libavcodec = ['avcodec', 'ws2_32', 'dl', 'avicap32', 'gdi32', 'psapi', 'ole32', 'strmiids', 'uuid', 'oleaut32', 'shlwapi', 'user32', 'dl', 'iconv', 'secur32', 'mingw32', 'SDL2main', 'SDL2', 'mingw32', 'SDL2main', 'SDL2', 'm', 'dinput8', 'dxguid', 'dxerr8', 'user32', 'gdi32', 'winmm', 'imm32', 'ole32', 'oleaut32', 'shell32', 'version', 'uuid', 'gcrypt', 'gpg-error', 'x265', 'stdc++', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'advapi32', 'shell32', 'user32', 'kernel32', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'x264', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vorbisenc', 'vorbis', 'ogg', 'opus', 'm', 'mp3lame', 'm', 'lzma', 'bz2', 'z', 'psapi', 'advapi32', 'shell32', 'swresample', 'm', 'avutil', 'm']
STLIB_libavdevice = ['avdevice', 'ws2_32', 'dl', 'avicap32', 'gdi32', 'psapi', 'ole32', 'strmiids', 'uuid', 'oleaut32', 'shlwapi', 'user32', 'dl', 'iconv', 'secur32', 'mingw32', 'SDL2main', 'SDL2', 'mingw32', 'SDL2main', 'SDL2', 'm', 'dinput8', 'dxguid', 'dxerr8', 'user32', 'gdi32', 'winmm', 'imm32', 'ole32', 'oleaut32', 'shell32', 'version', 'uuid', 'gcrypt', 'gpg-error', 'x265', 'stdc++', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'advapi32', 'shell32', 'user32', 'kernel32', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'x264', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vorbisenc', 'vorbis', 'ogg', 'opus', 'm', 'mp3lame', 'm', 'lzma', 'bz2', 'z', 'psapi', 'advapi32', 'shell32', 'avfilter', 'ws2_32', 'dl', 'avicap32', 'gdi32', 'psapi', 'ole32', 'strmiids', 'uuid', 'oleaut32', 'shlwapi', 'user32', 'dl', 'iconv', 'secur32', 'mingw32', 'SDL2main', 'SDL2', 'mingw32', 'SDL2main', 'SDL2', 'm', 'dinput8', 'dxguid', 'dxerr8', 'user32', 'gdi32', 'winmm', 'imm32', 'ole32', 'oleaut32', 'shell32', 'version', 'uuid', 'gcrypt', 'gpg-error', 'x265', 'stdc++', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'advapi32', 'shell32', 'user32', 'kernel32', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'x264', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vorbisenc', 'vorbis', 'ogg', 'opus', 'm', 'mp3lame', 'm', 'lzma', 'bz2', 'z', 'psapi', 'advapi32', 'shell32', 'swscale', 'm', 'postproc', 'avformat', 'ws2_32', 'dl', 'avicap32', 'gdi32', 'psapi', 'ole32', 'strmiids', 'uuid', 'oleaut32', 'shlwapi', 'user32', 'dl', 'iconv', 'secur32', 'mingw32', 'SDL2main', 'SDL2', 'mingw32', 'SDL2main', 'SDL2', 'm', 'dinput8', 'dxguid', 'dxerr8', 'user32', 'gdi32', 'winmm', 'imm32', 'ole32', 'oleaut32', 'shell32', 'version', 'uuid', 'gcrypt', 'gpg-error', 'x265', 'stdc++', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'advapi32', 'shell32', 'user32', 'kernel32', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'x264', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vorbisenc', 'vorbis', 'ogg', 'opus', 'm', 'mp3lame', 'm', 'lzma', 'bz2', 'z', 'psapi', 'advapi32', 'shell32', 'avcodec', 'ws2_32', 'dl', 'avicap32', 'gdi32', 'psapi', 'ole32', 'strmiids', 'uuid', 'oleaut32', 'shlwapi', 'user32', 'dl', 'iconv', 'secur32', 'mingw32', 'SDL2main', 'SDL2', 'mingw32', 'SDL2main', 'SDL2', 'm', 'dinput8', 'dxguid', 'dxerr8', 'user32', 'gdi32', 'winmm', 'imm32', 'ole32', 'oleaut32', 'shell32', 'version', 'uuid', 'gcrypt', 'gpg-error', 'x265', 'stdc++', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'advapi32', 'shell32', 'user32', 'kernel32', 'mingwthrd', 'mingw32', 'moldname', 'msvcrt', 'x264', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vpx', 'm', 'pthread', 'vorbisenc', 'vorbis', 'ogg', 'opus', 'm', 'mp3lame', 'm', 'lzma', 'bz2', 'z', 'psapi', 'advapi32', 'shell32', 'swresample', 'm', 'avutil', 'm']
STLIB_libbluray = ['bluray']
STLIB_luajit = ['luajit-5.1', 'm', 'iconv']
STLIB_rubberband = ['rubberband', 'stdc++']
STLIB_uchardet = ['uchardet', 'stdc++']
WINDRES = ['/mingw32/bin/windres']
ZSHDIR = '/local32/share/zsh/site-functions'
cfg_files = ['/build/mpv-git/build/config.h']
cprogram_PATTERN = '%s.exe'
cshlib_PATTERN = '%s.dll'
cstlib_PATTERN = 'lib%s.a'
define_key = []
implib_PATTERN = 'lib%s.dll.a'
known_deps = ['rpi', 'xss', 'static-build', 'gl-dxinterop', 'is_ffmpeg', 'is_libav', 'sndio', 'drm', 'sse4-intrinsics', 'egl-helpers', 'manpage-build', 'd3d-hwaccel', 'rsound', 'posix-or-mingw', 'rubberband', 'gl-wayland', 'ios-gl', 'gnuc', 'nanosleep', 'subprocess', 'clang-database', 'encoding', 'libsmbclient', 'pdf-build', 'libass-osd', 'cuda-hwaccel', 'glob-win32-replacement', 'mali-fbdev', 'libm', 'win32-internal-pthreads', 'dummy-osd', 'glibc-thread-name', 'noexecstack', 'termios', 'sdl2', 'stdatomic', 'libarchive', 'zlib', 'iconv', 'videotoolbox-hwaccel', 'lua', 'cdda', 'audiounit', 'libmpv-static', 'netbsd-thread-name', 'uchardet', 'gbm.h', 'vapoursynth-core', 'libavcodec', 'x11', 'videotoolbox-gl', 'dvdread', 'libmpv-shared', 'xinerama', 'cplayer', 'android-gl', 'oss-audio-sunaudio', 'librt', 'lcms2', 'sdl1', 'linux-fstatfs', 'direct3d', 'jpeg', 'caca', 'posix-spawn', 'os-win32', 'posix', 'debug-build', 'test', 'bsd-thread-name', 'vapoursynth-lazy', 'vaapi-egl', 'shm', 'dvdnav', 'openal', 'libav', 'xext', 'vdpau', 'libbluray', 'libass', 'jack', 'audio-input', 'wasapi', 'libdl', 'vaapi-x-egl', 'pthreads', 'build-date', 'xrandr', 'pulse', 'mingw', 'vf-dlopen-filters', 'tv-v4l2', 'opensles', 'standard-gl', 'html-build', 'dos-paths', 'gbm', 'avutil-imgcpy-uc', 'cplugins', 'alsa', 'fchmod', 'bsd-fstatfs', 'vdpau-hwaccel', 'oss-audio-native', 'vaapi-hwaccel-old', 'gl-x11', 'gcc-tls', 'any-gl', 'vaapi', 'vdpau-gl-x11', 'wayland', 'asm', 'egl-drm', 'vt.h', 'vaapi-drm', 'osx-thread-name', 'apple-remote', 'vaapi-hwaccel-new', 'gl-win32', 'videodev', 'libv4l2', 'win32-executable', 'dvbin', 'coreaudio', 'vaapi-hwaccel', 'vaapi-glx', 'win32', 'oss-audio-4front', 'tv', 'oss-audio', 'cocoa', 'egl-angle-lib', 'vapoursynth', 'plain-gl', 'sys_videoio_h', 'zsh-comp', 'libavdevice', 'atomics', 'egl-x11', 'gl-cocoa', 'dlopen', 'vaapi-wayland', 'egl-angle', 'c11-tls', 'android', 'vaapi-x11', 'xv', 'gl', 'optimize', 'glob']
macbundle_PATTERN = '%s.bundle'
satisfied_deps = ['uchardet', 'libavcodec', 'libbluray', 'static-build', 'gl-win32', 'luajit', 'gl-dxinterop', 'is_ffmpeg', 'sse4-intrinsics', 'dvdread', 'libass', 'manpage-build', 'd3d-hwaccel', 'posix-or-mingw', 'rubberband', 'win32-executable', 'wasapi', 'libdl', 'pthreads', 'cplayer', 'build-date', 'mingw', 'win32', 'lcms2', 'gnuc', 'direct3d', 'tv', 'subprocess', 'encoding', 'html-build', 'pdf-build', 'dos-paths', 'jpeg', 'os-win32', 'libass-osd', 'cuda-hwaccel', 'glob-win32-replacement', 'libavdevice', 'atomics', 'libm', 'win32-internal-pthreads', 'gcc-tls', 'noexecstack', 'dlopen', 'asm', 'c11-tls', 'dvdnav', 'stdatomic', 'libav', 'libarchive', 'zlib', 'gl', 'optimize', 'iconv', 'lua']

**Comment by wiiaboo** [comment]
@ASopH Don't hijack threads with a potentially different issue. And don't paste huge walls of text. Attach it as a .txt or inside a .zip. I don't see anything wrong with that paste either, so it's probably something completely unrelated.

**Comment by ASopH** [comment]
excuse.. my fail.. I'v got an issue wit mpv and don't read carefully ..

**Comment by projalepeno** [comment]
_cache.py here:

https://www.dropbox.com/s/qyd6om5cr6o2nhh/_cache.py?dl=0

**Comment by wiiaboo** [comment]
Delete x265.pc inside \local32\lib\pkgconfig\ to force recompilation. Stuff should work now.

**Comment by projalepeno** [comment]
Unfortunately still getting the same issue.  I deleted the x265.pc file and re-ran the script but no luck.  I also re-downloaded the entire suite and started over, but still get an issue.  The logs are here:  [logs.zip](https://0x0.st/4ls.zip)

Thanks again.

**Comment by wiiaboo** [comment]
Go to line 1368 of media-suite_compile.sh:
```
log build /usr/bin/python waf -j "${cpuCount:-1}"
```
and add a `-v` before the `-j`:
```
log build /usr/bin/python waf -v -j "${cpuCount:-1}"
```
Don't use update_suite.sh or it'll overwrite the change.

When it fails again, upload the logs.zip.

**Comment by projalepeno** [comment]
[error.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/785478/error.txt)

All relevant logs have been anonymously uploaded to https://0x0.st/4l6.zip
Copy and paste [logs.zip](https://0x0.st/4l6.zip) in the GitHub issue.

**Comment by wiiaboo** [comment]
OK, turns out it was an upstream bug. Should be fixed now.

**Comment by wiiaboo** [comment]
Don't need to delete anything, it was a bug in mpv's build system specifically.

**Comment by projalepeno** [comment]
tried running the batch file again and still fails at mpv
 [logs.zip](https://0x0.st/4UN.zip)

**Comment by wiiaboo** [comment]
That's also present in upstream CI builds, but that one I have no idea how to fix other than maybe disabling angle. Should be fixed temporarily with b6acedf until upstream fixes it.

**Comment by projalepeno** [comment]
mpv build works now.  thanks for your help today
