### ISSUE TITLE
Building opus-tools fails with OpenSSL BIO_meth issues

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#687]
```
Likely error:
H:/development/media-autobuild_suite-master/local32/lib/libopusurl.a(libopusurl_la-http.o):(.text+0x2a96): undefined reference to `BIO_meth_free'
H:/development/media-autobuild_suite-master/local32/lib/libopusurl.a(libopusurl_la-http.o):(.text+0x2b5d): undefined reference to `SSL_get0_param'
H:/development/media-autobuild_suite-master/local32/lib/libopusurl.a(libopusurl_la-http.o):(.text+0x2cc6): undefined reference to `BIO_meth_free'
H:/development/media-autobuild_suite-master/local32/lib/libopusurl.a(libopusurl_la-http.o):(.text+0x4680): undefined reference to `OPENSSL_init_ssl'
```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1596338/logs.zip)

**Comment by LigH-de** [comment]
After your latest release:

```
Likely error:
Making all in .
make[2]: Entering directory '/build/opus-tools-git/build-32bit'
  CCLD     opusenc.exe
  CCLD     opusdec.exe
libtool:   error: cannot find the library '/local32/lib/libssl.la' or unhandled argument '/local32/lib/libssl.la'
m
```

**Comment by wiiaboo** [comment]
Recompile opusfile.

**Comment by LigH-de** [comment]
That brings me back to the original issue.

**Comment by wiiaboo** [comment]
OK, nevermind, it's an upstream issue. opusurl libs aren't being retrieved.

**Comment by LigH-de** [comment]
Means, I should report it to xiph/opus-tools?

**Comment by wiiaboo** [comment]
I did already, in IRC, and it's fixed in another branch.

**Comment by LigH-de** [comment]
I still can't get it pass... after updating to the last suite version, I tried to force recompiling any more or less opus related software by deleting the following (possibly more than necessary, but hopefully not less):

- build/opusfile-git
- build/opus-tools-git
- build/libopusenc-git
- local32/libopus*.a
- local32/libopus*.la

Still, the same OpenSSL errors.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1602060/logs.zip)

Some libopusurl.a still exist in msys64/mingw{32|64}/lib but I did not dare to delete those manually...

**Comment by wiiaboo** [comment]
I can't reproduce the issue here anymore after 2c80212854e4835d8ffc7ad2ef3ab5959586e996.

**Comment by LigH-de** [comment]
For me, it's reproducable on two distinct PC's.

Time to completely re-install the whole suite?!

[logs.zip](https://0x0.st/sPDR.zip)

**Comment by wiiaboo** [comment]
Do `pkg-config --modversion openssl`. It should say "1.0.2n".

**Comment by LigH-de** [comment]
Yes, it does.

**Comment by LigH-de** [comment]
On my other PC, I deleted all subdirectories under /build and the whole content of /local32 and /local64; rebuilding "everything" made pacman detect more missing dependencies and installing several packets (e.g. many python2 modules)... but all audio tools were built, including opus, and most video tools (right now it's making ffmpeg).

The hierarchy of dependencies is complex. Sometimes it may be recommendable to start with a fresh foundation.

**Comment by wiiaboo** [comment]
Since I can't reproduce the issue there's no change I can suggest to fix it. If there's no other openssl installed anywhere I have no idea why your opusfile keeps getting compiled with openssl 1.1 symbols instead of 1.0.2.
